const KAPU_NETWORK = 'mainnet';
const KAPU_NODE_FOLDER = '/home/bitnow/kapu-core';
const KAPU_SNAPSHOT_SOURCE = '/home/bitnow/.kapu/snapshots';
const KAPU_SNAPSHOT_DESTINATION = '/opt/nginx/snapshot.kapunode.net';
const DELETE_OLDER_THAN_SECONDS = 600; //2 days 172800, 1 day 86400
const EXECUTE_EVERY_SECONDS = 300;

module.exports = {
    KAPU_NETWORK: KAPU_NETWORK,
    KAPU_NODE_FOLDER: KAPU_NODE_FOLDER,
    KAPU_SNAPSHOT_SOURCE: KAPU_SNAPSHOT_SOURCE,
    KAPU_SNAPSHOT_DESTINATION: KAPU_SNAPSHOT_DESTINATION,
    DELETE_OLDER_THAN_SECONDS: DELETE_OLDER_THAN_SECONDS,
    EXECUTE_EVERY_SECONDS: EXECUTE_EVERY_SECONDS
};
